### ISSUE TITLE
Generics method instead of dynamic

### ISSUE THREAD

**Issue by binSaed** [abdullahmansss/udemy#1]
https://github.com/abdullahmansss/udemy/blob/150096c4f72f5d11a6ed2354348b0cae689c2ce0/lib/shared/network/local/cache_helper.dart#L18
use generics method instead of dynamic
i will put the same method with generics in a new comment

**Comment by binSaed** [comment]
```dart
  static T getData<T>({
    @required String key,
  }) {
    return sharedPreferences.get(key) as T;
  }

```

**Comment by binSaed** [comment]
or like this 

```dart
  static T getData<T>({
    @required String key,
  }) {
    if (T is String) return sharedPreferences.getString(key) as T;
    if (T is int) return sharedPreferences.getInt(key) as T;
    if (T is bool) return sharedPreferences.getBool(key) as T;

    return sharedPreferences.get(key) as T;
  }

```

**Comment by binSaed** [comment]
**_This issue is only for learning purpose_**

**Comment by abdullahmansss** [comment]
مش كل الحلول ولا كل الكلام ينفع يتقال يا صديقي، لازم نكون عالهادي عشان اللي بيشوف كتير، في حلول متقدمة متنفعش للكل في كل الأوقات، جزاكم الله خيرا

**Comment by binSaed** [comment]
بعتذرلك وحقيقي والله الغرض من المشكله الي فتحتها للتعلم فقط
مش قصدي مذايده والله
انا بالصدفه شوفت جزء من الفيديو الخاص بالشيرد بيرفرنس
بشوف منو طريقة الشرح من اكتر من شخص 
عشان انمي عندي مهارات الشرح للغير لاني شايفها مهاره مهمه
فاما لقيتك عامل ميثود ال setData 
بتشتغل بناء ع القيمه الي بتجلها
فقولت اعمل ال getData 
زيها 

بس حقيقي انت عندك حق لو كل حاجه اتقالت الكورس هيكون اكتر من 1000 ساعه😅

**Comment by binSaed** [comment]
تقبل اعتزاري وانت زي اخي الكبير 
انا فاكر اني من اكتر من سنتين بعتلك اني بدور علي شغل 
وانا ساعتها كنت شغال اندرويد نيتف فقط وانت متأخرتش
